# Form implementation generated from reading ui file 'ui/addDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddDialog(object):
    def setupUi(self, AddDialog):
        AddDialog.setObjectName("AddDialog")
        AddDialog.resize(389, 174)
        self.formLayout = QtWidgets.QFormLayout(AddDialog)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(AddDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameField = QtWidgets.QLineEdit(AddDialog)
        self.nameField.setObjectName("nameField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameField)
        self.fleetIdLabel = QtWidgets.QLabel(AddDialog)
        self.fleetIdLabel.setObjectName("fleetIdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fleetIdLabel)
        self.fleetIdField = QtWidgets.QLineEdit(AddDialog)
        self.fleetIdField.setObjectName("fleetIdField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fleetIdField)
        self.deviceIdLabel = QtWidgets.QLabel(AddDialog)
        self.deviceIdLabel.setObjectName("deviceIdLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.deviceIdLabel)
        self.deviceIdField = QtWidgets.QLineEdit(AddDialog)
        self.deviceIdField.setObjectName("deviceIdField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deviceIdField)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)

        self.retranslateUi(AddDialog)
        self.buttonBox.accepted.connect(AddDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddDialog)

    def retranslateUi(self, AddDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDialog.setWindowTitle(_translate("AddDialog", "Dialog"))
        self.nameLabel.setText(_translate("AddDialog", "Name:"))
        self.nameField.setStatusTip(_translate("AddDialog", "An informal name for the radio, i.e. \'Truck Radio\'."))
        self.fleetIdLabel.setText(_translate("AddDialog", "Fleet ID:"))
        self.deviceIdLabel.setText(_translate("AddDialog", "Device ID:"))
