# Form implementation generated from reading ui file 'ui/queryLocationDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QueryLocationDialog(object):
    def setupUi(self, QueryLocationDialog):
        QueryLocationDialog.setObjectName("QueryLocationDialog")
        QueryLocationDialog.resize(400, 147)
        self.formLayout = QtWidgets.QFormLayout(QueryLocationDialog)
        self.formLayout.setObjectName("formLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(QueryLocationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        self.label_2 = QtWidgets.QLabel(QueryLocationDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label = QtWidgets.QLabel(QueryLocationDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.fleetIdSpinBox = QtWidgets.QSpinBox(QueryLocationDialog)
        self.fleetIdSpinBox.setMinimum(100)
        self.fleetIdSpinBox.setMaximum(349)
        self.fleetIdSpinBox.setObjectName("fleetIdSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fleetIdSpinBox)
        self.deviceIdSpinBox = QtWidgets.QSpinBox(QueryLocationDialog)
        self.deviceIdSpinBox.setMinimum(1000)
        self.deviceIdSpinBox.setMaximum(4999)
        self.deviceIdSpinBox.setObjectName("deviceIdSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deviceIdSpinBox)

        self.retranslateUi(QueryLocationDialog)
        self.buttonBox.accepted.connect(QueryLocationDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(QueryLocationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QueryLocationDialog)

    def retranslateUi(self, QueryLocationDialog):
        _translate = QtCore.QCoreApplication.translate
        QueryLocationDialog.setWindowTitle(_translate("QueryLocationDialog", "Query Radio Location"))
        self.label_2.setText(_translate("QueryLocationDialog", "Fleet ID:"))
        self.label.setText(_translate("QueryLocationDialog", "Device ID:"))
