# Form implementation generated from reading ui file 'ui/textDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TextDialog(object):
    def setupUi(self, TextDialog):
        TextDialog.setObjectName("TextDialog")
        TextDialog.resize(400, 253)
        self.formLayout = QtWidgets.QFormLayout(TextDialog)
        self.formLayout.setObjectName("formLayout")
        self.fleetIdLabel = QtWidgets.QLabel(TextDialog)
        self.fleetIdLabel.setObjectName("fleetIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fleetIdLabel)
        self.fleetIdSpinBox = QtWidgets.QSpinBox(TextDialog)
        self.fleetIdSpinBox.setMinimum(100)
        self.fleetIdSpinBox.setMaximum(349)
        self.fleetIdSpinBox.setObjectName("fleetIdSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fleetIdSpinBox)
        self.deviceIdLabel = QtWidgets.QLabel(TextDialog)
        self.deviceIdLabel.setObjectName("deviceIdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.deviceIdLabel)
        self.deviceIdSpinBox = QtWidgets.QSpinBox(TextDialog)
        self.deviceIdSpinBox.setMinimum(1000)
        self.deviceIdSpinBox.setMaximum(4999)
        self.deviceIdSpinBox.setObjectName("deviceIdSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deviceIdSpinBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(TextDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.buttonBox)
        self.messageLabel = QtWidgets.QLabel(TextDialog)
        self.messageLabel.setObjectName("messageLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.messageLabel)
        self.radioMessage = QtWidgets.QLineEdit(TextDialog)
        self.radioMessage.setMaxLength(4096)
        self.radioMessage.setObjectName("radioMessage")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioMessage)
        self.broadcastCheckBox = QtWidgets.QCheckBox(TextDialog)
        self.broadcastCheckBox.setObjectName("broadcastCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.broadcastCheckBox)

        self.retranslateUi(TextDialog)
        self.buttonBox.accepted.connect(TextDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(TextDialog.reject) # type: ignore
        self.broadcastCheckBox.toggled['bool'].connect(self.fleetIdSpinBox.setDisabled) # type: ignore
        self.broadcastCheckBox.toggled['bool'].connect(self.deviceIdSpinBox.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TextDialog)

    def retranslateUi(self, TextDialog):
        _translate = QtCore.QCoreApplication.translate
        TextDialog.setWindowTitle(_translate("TextDialog", "Text Radio"))
        self.fleetIdLabel.setText(_translate("TextDialog", "Fleet ID:"))
        self.deviceIdLabel.setText(_translate("TextDialog", "Device ID:"))
        self.messageLabel.setText(_translate("TextDialog", "Message:"))
        self.broadcastCheckBox.setToolTip(_translate("TextDialog", "When checked Fleet ID and Device ID are disabled."))
        self.broadcastCheckBox.setText(_translate("TextDialog", "Broadcast"))
