name: Release KConsole
on:
  push:
    branches:
      - workflows
    tags:
      - '*'
env:
  version: "0.1.1"

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install pywin32 if on Windows
        run: |
          pip install --upgrade pywin32-ctypes
          pip install --upgrade pefile
        if: matrix.os == 'windows-latest'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: pipenv install
        run: pipenv install --system --dev

      - name: pyinstaller
        run: pyinstaller kconsole.spec

      - name: Archive Release Binaries
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: kconsole-${{ matrix.os }}-${{ env.version }}.zip
          path: dist/kconsole/

      - name: Upload Release Binaries
        uses: actions/upload-artifact@v3.1.0
        with:
          name: kconsole-${{ matrix.os }}-${{ env.version }}
          path: kconsole-${{ matrix.os }}-${{ env.version }}.zip
