name: Release KConsole
on:
  push:
    branches:
      - workflows
    tags:
      - '*'

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: install pipenv
        run: pip install pipenv

      - name: pipenv install
        run: pipenv install --system --dev

      - name: pyinstaller
        run: pyinstaller kconsole.spec

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: kconsole-${{ matrix.os }}
          path: |
           dist
           !dist/kconsole/kconsole/ui/resources/
